"""empty message

Revision ID: 0edec8db6879
Revises: a0a8ee54e116
Create Date: 2022-04-12 14:51:37.590132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edec8db6879'
down_revision = 'a0a8ee54e116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('DateW', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'DateW')
    # ### end Alembic commands ###
