"""empty message

Revision ID: 20b0fff095fd
Revises: 88d1550319f7
Create Date: 2022-03-15 11:16:30.724149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b0fff095fd'
down_revision = '88d1550319f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('sopran', sa.String(length=30), nullable=True))
    op.drop_constraint('player_name_key', 'player', type_='unique')
    op.create_unique_constraint(None, 'player', ['sopran'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.create_unique_constraint('player_name_key', 'player', ['name'])
    op.drop_column('player', 'sopran')
    # ### end Alembic commands ###
