"""empty message

Revision ID: 4adcf5654199
Revises: 896706a7e658
Create Date: 2022-04-13 11:25:55.356055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4adcf5654199'
down_revision = '896706a7e658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('ruolo', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'ruolo')
    # ### end Alembic commands ###
