"""empty message

Revision ID: 68164424f40c
Revises: 13a4930a17f0
Create Date: 2022-04-13 11:24:03.187012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68164424f40c'
down_revision = '13a4930a17f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contract', sa.Column('N_maglia', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'N_maglia')
    op.drop_table('category')
    # ### end Alembic commands ###
