"""empty message

Revision ID: 6e8c6310207a
Revises: 879bc074a4f2
Create Date: 2022-04-19 12:24:51.767370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8c6310207a'
down_revision = '879bc074a4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squadra', sa.Integer(), nullable=True),
    sa.Column('Punti', sa.Integer(), nullable=False),
    sa.Column('Partite_Giocate', sa.Integer(), nullable=False),
    sa.Column('Partite_Vinte', sa.Integer(), nullable=False),
    sa.Column('Partite_Paregg', sa.Integer(), nullable=False),
    sa.Column('Partite_Perse', sa.Integer(), nullable=False),
    sa.Column('Goal_Fatti', sa.Integer(), nullable=False),
    sa.Column('Goal_Subiti', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['squadra'], ['squad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifica')
    # ### end Alembic commands ###
