"""empty message

Revision ID: 879bc074a4f2
Revises: 4adcf5654199
Create Date: 2022-04-13 11:26:34.464144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879bc074a4f2'
down_revision = '4adcf5654199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('naz', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'naz')
    # ### end Alembic commands ###
