"""empty message

Revision ID: 896706a7e658
Revises: 68164424f40c
Create Date: 2022-04-13 11:25:09.247798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896706a7e658'
down_revision = '68164424f40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('ruolo', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'ruolo')
    # ### end Alembic commands ###
