"""empty message

Revision ID: a1275b2e6d44
Revises: bfe8f7d9cfb9
Create Date: 2022-03-14 09:56:49.195012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1275b2e6d44'
down_revision = 'bfe8f7d9cfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'prov',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('squad', 'bornDate',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('squad', 'bornDate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('squad', 'prov',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
