"""empty message

Revision ID: bfe8f7d9cfb9
Revises: 9180cee679e9
Create Date: 2022-03-14 09:53:45.989247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe8f7d9cfb9'
down_revision = '9180cee679e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('nick', sa.String(length=30), nullable=False))
    op.add_column('squad', sa.Column('prov', sa.String(), nullable=False))
    op.add_column('squad', sa.Column('bornDate', sa.Integer(), nullable=False))
    op.drop_column('squad', 'age')
    op.drop_column('squad', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('squad', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('squad', 'bornDate')
    op.drop_column('squad', 'prov')
    op.drop_column('squad', 'nick')
    # ### end Alembic commands ###
