"""empty message

Revision ID: d1cc7660ff22
Revises: 20b0fff095fd
Create Date: 2022-03-28 10:45:26.755303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cc7660ff22'
down_revision = '20b0fff095fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('squad', sa.Column('Pres', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'squad', ['nick'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squad', type_='unique')
    op.drop_column('squad', 'Pres')
    # ### end Alembic commands ###
